(*
  (C) Vitaly Smirnov [VSdev]
  mrmaybelately@gmail.com
  2022-2023
*)
  VSLogoBy1 = 'by Vitaly Smirnov';

  VSLogoStrings1: {array of AnsiString}TStrings = (
    '___         ___ ___________                            ',
    '\  \       /  //  _______  \       ___                 ',
    ' \  \     /  //  /       \__\      | |                 ',
    '  \  \   /  / \  \_________    ___ | |  _____ __     __',
    '   \  \_/  /   \_________  \  / _ \| | / ___ \\ \   / /',
    '    \     /   ___        \  \/ / \   |/ ______\\ \_/ / ',
    '     \   /    \  \_______/  /\ \_/   |\ \_____  \   /  ',
    '      \_/      \___________/  \___/|_| \_____/   \_/   '
  );

  VSLogoStrings2: {array of AnsiString}TStrings = (
    '_____________',
    '\           /',
    ' \  VSdev  / ',
    '  \_______/  ',
    '   \ /-\ /   ',
    '    \\_//    ',
    '     / \     ',
    '     \_/     ',
    '     / \     ',
    '    /   \    '
  );


  VSAboutStrings1: {array of AnsiString}TStrings = (
    '(c) Vitaly Smirnov [VSdev]',
    'mrmaybelately@gmail.com',
    '2022-2023'
  );


